name: Correccion de ip para subida en main
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Script
      run: sh ip_fix.sh
