name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "192.168.0.123:4001"
          replace: "192.168.0.133:4001"
          regex: false
          include: "MES/frontend"
